# The Secrect Actions GitHub example has three steps
name: Print Secerts

on:
  watch:
    types: [started]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Show how to print unmasked GitHub secrets to the console
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.YOUTH_HEADER1 }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.YOUTH_HEADER1}} | sed 's/./& /g' 
          echo ${{secrets.YOUTH_HEADER2}} | sed 's/./& /g' 
          echo ${{secrets.YOUTH_HEADER3}} | sed 's/./& /g' 
